format = """
[](#1e1e2e)\
$os\
$username\
$hostname\
[](bg:#313244 fg:#1e1e2e)\
$directory\
[](fg:#313244 bg:#45475a)\
$git_branch\
$git_status\
[](fg:#45475a bg:#89b4fa)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
[](fg:#89b4fa bg:#94e2d5)\
$docker_context\
[](fg:#94e2d5 bg:#cba6f7)\
$time\
[ ](fg:#cba6f7)\
"""
command_timeout = 5000

[username]
show_always = true
style_user = "bg:#1e1e2e fg:#cdd6f4"
style_root = "bg:#1e1e2e fg:#f38ba8"
format = '[$user]($style)'

[hostname]
ssh_only = false
style = "bg:#1e1e2e fg:#cdd6f4"
format = '[@$hostname ]($style)'

[os]
disabled = false
style = "bg:#1e1e2e fg:#cdd6f4"
format = '[$symbol]($style)'

[os.symbols]
Windows = "󰍲 "
Ubuntu = " "
Debian = " "
Raspbian = " "
Mint = "󰣭 "
Macos = " "
Manjaro = " "
Linux = " "
Gentoo = "󰣨 "
Fedora = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
NixOS = " "
Redhat = "󱄛 "
SUSE = " "

[directory]
style = "bg:#313244 fg:#cdd6f4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#94e2d5 fg:#1e1e2e"
format = '[ $symbol $context ]($style)$path'

[elixir]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = " "
style = "bg:#45475a fg:#cdd6f4"
format = '[ $symbol$branch ]($style)'

[git_status]
style = "bg:#45475a fg:#cdd6f4"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#1e1e2e fg:#f9e2af"
format = '[ $symbol(\($virtualenv\) )]($style)'

[rust]
symbol = " "
style = "bg:#89b4fa fg:#1e1e2e"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#cba6f7 fg:#1e1e2e"
format = '[ $time ]($style)'
